---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: flake8
      - id: pretty-format-json
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: isort
        stages: [commit]
        name: isort_format
        entry: pipenv run isort
        language: system
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8
